#!/usr/bin/env python3
"""
Embedded C Code Generator from Datasheet Register Maps.
Generates MISRA-C compliant header files containing peripheral structs,
base addresses, bit positions, masks, and bare-metal access macros.
"""

import sys
import json
import argparse
import re

def clean_name(name):
    """Clean register/peripheral names for C compatibility."""
    # Strip parentheticals
    name = re.sub(r'\(.*?\)', '', name)
    # Replace invalid C chars with underscore
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Strip leading/trailing underscores
    name = name.strip('_')
    # Replace multiple underscores with single one
    name = re.sub(r'_+', '_', name)
    # Ensure it doesn't start with a number
    if name and name[0].isdigit():
        name = "_" + name
    return name.upper()

def parse_offset(offset_str):
    """Convert offset string (e.g. 0x04 or 4) to integer."""
    try:
        offset_str = offset_str.strip().lower()
        if offset_str.startswith("0x"):
            return int(offset_str, 16)
        return int(offset_str)
    except ValueError:
        return None

def parse_bit_range(bit_str):
    """Parse bit string (e.g. "13" or "15:12") to (start, end)."""
    bit_str = bit_str.strip()
    if ":" in bit_str:
        parts = bit_str.split(":")
        try:
            high = int(parts[0])
            low = int(parts[1])
            return min(high, low), max(high, low)
        except ValueError:
            return None
    else:
        try:
            bit = int(bit_str)
            return bit, bit
        except ValueError:
            return None

def generate_header(data, peripheral_name):
    """Generate C header file content."""
    peripheral_name = clean_name(peripheral_name)
    registers = data.get("registers", [])
    peripherals = data.get("peripherals", {})
    
    # Sort registers by offset
    valid_registers = []
    for reg in registers:
        offset_val = parse_offset(reg.get("offset", ""))
        if offset_val is not None:
            valid_registers.append((offset_val, reg))
            
    valid_registers.sort(key=lambda x: x[0])
    
    # Check if offsets are actually absolute addresses
    is_absolute = False
    inferred_base = None
    if valid_registers:
        min_addr = valid_registers[0][0]
        if min_addr >= 0x10000:
            is_absolute = True
            inferred_base = min_addr & ~0xFFF
            
    # Get base address
    base_addr = None
    if peripheral_name in peripherals:
        base_addr = peripherals[peripheral_name].get("base_address", None)
    else:
        # Search case-insensitively
        for p_name, p_data in peripherals.items():
            if p_name.upper() == peripheral_name.upper():
                base_addr = p_data.get("base_address", None)
                break
                
    if base_addr is not None:
        base_addr_val = parse_offset(base_addr)
    else:
        if is_absolute:
            base_addr_val = inferred_base
            base_addr = f"0x{inferred_base:08X}"
        else:
            base_addr_val = 0
            base_addr = "0x40000000" # Default fallback
            
    # Normalize offsets to be relative to the base address
    normalized_registers = []
    for offset_val, reg in valid_registers:
        if is_absolute or offset_val >= base_addr_val:
            rel_offset = offset_val - base_addr_val
        else:
            rel_offset = offset_val
        normalized_registers.append((rel_offset, reg))
        
    valid_registers = normalized_registers
                
    lines = [
        f"/**",
        f" * @file {peripheral_name.lower()}_regs.h",
        f" * @brief Auto-generated register definitions for {peripheral_name}",
        f" * @note Generated by danielou-ai RAG parser.",
        f" */",
        f"",
        f"#ifndef {peripheral_name}_REGS_H_",
        f"#define {peripheral_name}_REGS_H_",
        f"",
        f"#include <stdint.h>",
        f"",
        f"/* Hardware access macro definition */",
        f"#ifndef __IO",
        f"  #define __IO volatile",
        f"#endif",
        f"",
        f"/**",
        f"  * @brief {peripheral_name} registers struct mapping",
        f"  */",
        f"typedef struct {{",
    ]
    
    # Generate struct members with padding for offsets
    current_offset = 0
    reserved_idx = 0
    
    for offset, reg in valid_registers:
        reg_name = clean_name(reg.get("name", ""))
        
        # Check if we need to insert reserved padding
        if offset > current_offset:
            gap = offset - current_offset
            # Ensure gap is 4-byte aligned
            if gap % 4 == 0:
                words = gap // 4
                lines.append(f"  __IO uint32_t RESERVED{reserved_idx}[{words}]; /*!< Padding to offset 0x{offset:02X} */")
                reserved_idx += 1
            else:
                # Byte-level alignment if not 4-byte aligned (rare for 32-bit registers)
                lines.append(f"  __IO uint8_t  RESERVED_BYTES{reserved_idx}[{gap}];")
                reserved_idx += 1
            current_offset = offset
            
        if offset == current_offset:
            desc = reg.get("description", "").replace("\n", " ")
            lines.append(f"  __IO uint32_t {reg_name}; /*!< {reg_name} register, Offset: 0x{offset:02X}. {desc} */")
            current_offset += 4
            
    lines.append(f"}} {peripheral_name}_TypeDef;")
    lines.append("")
    
    # Base Address definition
    lines.append(f"/* Peripheral Base Address */")
    lines.append(f"#ifdef MOCK_HARDWARE")
    lines.append(f"  extern uint8_t mock_{peripheral_name.lower()}_memory[];")
    lines.append(f"  #define {peripheral_name}_BASE_ADDR ((uintptr_t)mock_{peripheral_name.lower()}_memory)")
    lines.append(f"#else")
    lines.append(f"  #define {peripheral_name}_BASE_ADDR ({base_addr}U)")
    lines.append(f"#endif")
    lines.append(f"#define {peripheral_name} (({peripheral_name}_TypeDef *){peripheral_name}_BASE_ADDR)")
    lines.append("")
    
    # Mock Reset helper function
    lines.append(f"#ifdef MOCK_HARDWARE")
    lines.append(f"/**")
    lines.append(f"  * @brief Reset all mock registers for {peripheral_name} to 0")
    lines.append(f"  */")
    lines.append(f"static inline void {peripheral_name.lower()}_mock_reset(void) {{")
    lines.append(f"    uint8_t *ptr = mock_{peripheral_name.lower()}_memory;")
    lines.append(f"    for (unsigned int i = 0; i < sizeof({peripheral_name}_TypeDef); i++) {{")
    lines.append(f"        ptr[i] = 0;")
    lines.append(f"    }}")
    lines.append(f"}}")
    lines.append(f"#endif")
    lines.append("")
    
    # Generate bitfield constants
    lines.append(f"/* Register Bitfield Positions and Masks */")
    
    for offset, reg in valid_registers:
        reg_name = clean_name(reg.get("name", ""))
        fields = reg.get("fields", [])
        if not fields:
            continue
            
        lines.append(f"/* {reg_name} Bitfields */")
        for f in fields:
            f_name = clean_name(f.get("name", ""))
            # Skip reserved fields
            if f_name.lower() == "reserved":
                continue
                
            bit_range = parse_bit_range(f.get("bits", ""))
            if not bit_range:
                continue
                
            low_bit, high_bit = bit_range
            pos_macro = f"{peripheral_name}_{reg_name}_{f_name}_Pos"
            msk_macro = f"{peripheral_name}_{reg_name}_{f_name}_Msk"
            
            lines.append(f"#define {pos_macro:<45} ({low_bit}U)")
            
            # Calculate mask
            span = high_bit - low_bit + 1
            mask_val = (1 << span) - 1
            lines.append(f"#define {msk_macro:<45} (0x{mask_val:X}U << {pos_macro})")
            lines.append(f"#define {peripheral_name}_{reg_name}_{f_name:<41} {msk_macro}")
            
        lines.append("")
        
    # Helper inline functions/macros (without dynamic allocation)
    lines.append("/* Safe Register Manipulation Inline Helper Functions */")
    lines.append(f"static inline void {peripheral_name.lower()}_set_bits(__IO uint32_t *reg, uint32_t mask) {{")
    lines.append("    *reg |= mask;")
    lines.append("}")
    lines.append("")
    lines.append(f"static inline void {peripheral_name.lower()}_clear_bits(__IO uint32_t *reg, uint32_t mask) {{")
    lines.append("    *reg &= ~mask;")
    lines.append("}")
    lines.append("")
    lines.append(f"static inline void {peripheral_name.lower()}_modify_bits(__IO uint32_t *reg, uint32_t mask, uint32_t val) {{")
    lines.append("    *reg = (*reg & ~mask) | val;")
    lines.append("}")
    lines.append("")
    
    lines.append(f"#endif /* {peripheral_name}_REGS_H_ */")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate bare-metal Embedded C register headers from JSON map.")
    parser.add_argument("json_file", help="Path to register map JSON file (from datasheet parser)")
    parser.add_argument("peripheral", help="Name of the peripheral (e.g. USART1)")
    parser.add_argument("-o", "--output", help="Path to output header file (default: stdout)", default=None)
    
    args = parser.parse_args()
    
    try:
        with open(args.json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON file: {e}", file=sys.stderr)
        sys.exit(1)
        
    header_content = generate_header(data, args.peripheral)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"[*] C header file successfully generated at: {args.output}")
    else:
        print(header_content)

if __name__ == "__main__":
    main()
